# Yarn 4 (Berry) Configuration
yarnPath: .yarn/releases/yarn-4.11.0.cjs

# Use node-modules linker for React Native compatibility
nodeLinker: node-modules

# Control hoisting behavior - workspaces mode keeps dependencies in each workspace
# This replaces the old nohoist configuration from Yarn Classic
nmHoistingLimits: workspaces

# Enable modern compression for faster installs
compressionLevel: mixed

# Enable global cache for faster installs across projects
enableGlobalCache: true

# Network settings for better reliability
httpTimeout: 600000
networkConcurrency: 16

# Logging - reduce noise
logFilters:
  - code: YN0013
    level: discard

# Disable telemetry
enableTelemetry: false
