name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) should this feature target?
      multiple: true
      options:
        - All platforms
        - iOS (React Native)
        - Android (React Native)
        - Web (React Native Web)
        - Desktop (Tauri)
        - Windows (React Native Windows)
        - macOS (React Native macOS)
        - tvOS
        - Android TV
        - Browser Extension
        - Next.js
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions you've considered
      placeholder: What other approaches have you thought about?

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        // Example code or usage
        import { newFeature } from '@my-app/app';

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Designs
      description: If applicable, add mockups, wireframes, or design concepts
      placeholder: Drag and drop images here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
